[build]
builder = "NIXPACKS"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PORT = "5001"
FLASK_ENV = "production"
DEBUG = "false"
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"